apiVersion: apps/v1
kind: Deployment
metadata:
  name: myly3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myly3
  template:
    metadata:
      labels:
        app: myly3
    spec:
      containers:
      - image: okteto.dev/myly3:latest
        name: myly3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: AUUID
          value: "2c49ad6b-6205-42ce-b364-143a82958b13"
