apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiok1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uiok1
  template:
    metadata:
      labels:
        app: uiok1
    spec:
      containers:
      - image: okteto.dev/uiok1:latest
        name: uiok1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: AUUID
          value: "30cc16cd-a2b6-4f8f-8da1-472a6d593ec6"
