apiVersion: v1
kind: Service
metadata:
  name: myly3
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "myly3"
    port: 8080
  selector:
    app: myly3
