apiVersion: v1
kind: Service
metadata:
  name: uiok1
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "uiok1"
    port: 8080
  selector:
    app: uiok1
