apiVersion: v1
kind: Service
metadata:
  name: okmi4
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okmi4"
    port: 8080
  selector:
    app: okmi4
